BaseUrl= "http://example.com/"
LanguageCode= ""
Title= "ertkjern.github.io"
paginate = 5
Copyright = "All rights reserved - 2017"
canonifyurls = true
theme = "casper"

[params]
  description = "My Tech Blog"
  cover = "images/cover.jpg"
  author = "Ørjan Ertkjern"
  authorlocation = "Bergen, Norway"
  #authorwebsite = ""
  bio= "Front-End Developer/Interaction Designer @ Evry"
  logo = "images/logo.png"
  #googleAnalyticsUserID = ""
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = "http://feeds.feedburner.com/"
  githubName = "ertkjern"
  twitterName = "ertkjern"
  # facebookName = ""
  linkedinName = "ørjan-ertkjern-20496b64"
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false
  [params.social]
    twitter = "your_twitter"
	
[[menu.main]]
  name = "My Blog"
  weight = -120
  identifier = "blog"
  url = "/"